
package fr.alma.soa.boutique.application.webservice.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "boutiqueServices", targetNamespace = "http://impl.webservice.application.boutique.soa.alma.fr", wsdlLocation = "http://localhost:9763/services/boutiqueServices?wsdl")
public class BoutiqueServices
    extends Service
{

    private final static URL BOUTIQUESERVICES_WSDL_LOCATION;
    private final static WebServiceException BOUTIQUESERVICES_EXCEPTION;
    private final static QName BOUTIQUESERVICES_QNAME = new QName("http://impl.webservice.application.boutique.soa.alma.fr", "boutiqueServices");
    private static BoutiqueServices boutiqueServices = null;
    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9763/services/boutiqueServices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOUTIQUESERVICES_WSDL_LOCATION = url;
        BOUTIQUESERVICES_EXCEPTION = e;
    }
    
    public static BoutiqueServices getInstance(){
    	if(boutiqueServices==null){
    		boutiqueServices = new BoutiqueServices();
    	}
    	return boutiqueServices;
    }

    private BoutiqueServices() {
        super(__getWsdlLocation(), BOUTIQUESERVICES_QNAME);
    }

    private BoutiqueServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOUTIQUESERVICES_QNAME, features);
    }

    private BoutiqueServices(URL wsdlLocation) {
        super(wsdlLocation, BOUTIQUESERVICES_QNAME);
    }

    private BoutiqueServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOUTIQUESERVICES_QNAME, features);
    }

    private BoutiqueServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    private BoutiqueServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BoutiqueServicesPortType
     */
    @WebEndpoint(name = "boutiqueServicesHttpsSoap11Endpoint")
    public BoutiqueServicesPortType getBoutiqueServicesHttpsSoap11Endpoint() {
        return super.getPort(new QName("http://impl.webservice.application.boutique.soa.alma.fr", "boutiqueServicesHttpsSoap11Endpoint"), BoutiqueServicesPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BoutiqueServicesPortType
     */
    @WebEndpoint(name = "boutiqueServicesHttpsSoap11Endpoint")
    public BoutiqueServicesPortType getBoutiqueServicesHttpsSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.webservice.application.boutique.soa.alma.fr", "boutiqueServicesHttpsSoap11Endpoint"), BoutiqueServicesPortType.class, features);
    }

    /**
     * 
     * @return
     *     returns BoutiqueServicesPortType
     */
    @WebEndpoint(name = "boutiqueServicesHttpSoap11Endpoint")
    public BoutiqueServicesPortType getBoutiqueServicesHttpSoap11Endpoint() {
        return super.getPort(new QName("http://impl.webservice.application.boutique.soa.alma.fr", "boutiqueServicesHttpSoap11Endpoint"), BoutiqueServicesPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BoutiqueServicesPortType
     */
    @WebEndpoint(name = "boutiqueServicesHttpSoap11Endpoint")
    public BoutiqueServicesPortType getBoutiqueServicesHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.webservice.application.boutique.soa.alma.fr", "boutiqueServicesHttpSoap11Endpoint"), BoutiqueServicesPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOUTIQUESERVICES_EXCEPTION!= null) {
            throw BOUTIQUESERVICES_EXCEPTION;
        }
        return BOUTIQUESERVICES_WSDL_LOCATION;
    }

}
