
package fr.alma.soa.boutique.application.webservice.impl;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import fr.alma.soa.boutique.domaine.model.dto.CategoryDto;
import fr.alma.soa.boutique.domaine.model.dto.CustomerDto;
import fr.alma.soa.boutique.domaine.model.dto.ProductDto;
import fr.alma.soa.boutique.domaine.model.dto.ShoppingCartDto;
import fr.alma.soa.boutique.domaine.service.xsd.CategoryService;
import fr.alma.soa.boutique.domaine.service.xsd.CustomerService;
import fr.alma.soa.boutique.domaine.service.xsd.ProductService;
import fr.alma.soa.boutique.domaine.service.xsd.ShoppingCartService;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "boutiqueServicesPortType", targetNamespace = "http://impl.webservice.application.boutique.soa.alma.fr")
@XmlSeeAlso({
    fr.alma.soa.boutique.application.webservice.impl.ObjectFactory.class,
   // fr.alma.soa.boutique.domaine.model.dto.ObjectFactory.class,
    fr.alma.soa.boutique.domaine.service.xsd.ObjectFactory.class,
    fr.alma.soa.presentation.util.xsd.ObjectFactory.class
})
public interface BoutiqueServicesPortType {


    /**
     * 
     * @param product
     * @param customer
     * @return
     *     returns fr.alma.soa.boutique.domaine.model.dto.xsd.ShoppingCartDto
     */
    @WebMethod(action = "urn:removeProductFromCart")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeProductFromCart", targetNamespace = "http://impl.webservice.application.boutique.soa.alma.fr", className = "fr.alma.soa.boutique.application.webservice.impl.RemoveProductFromCart")
    @ResponseWrapper(localName = "removeProductFromCartResponse", targetNamespace = "http://impl.webservice.application.boutique.soa.alma.fr", className = "fr.alma.soa.boutique.application.webservice.impl.RemoveProductFromCartResponse")
    public ShoppingCartDto removeProductFromCart(
        @WebParam(name = "customer", targetNamespace = "")
        CustomerDto customer,
        @WebParam(name = "product", targetNamespace = "")
        ProductDto product);

    /**
     * 
     * @param categoryService
     */
    @WebMethod(action = "urn:setCategoryService")
    @Oneway
    @RequestWrapper(localName = "setCategoryService", targetNamespace = "http://impl.webservice.application.boutique.soa.alma.fr", className = "fr.alma.soa.boutique.application.webservice.impl.SetCategoryService")
    public void setCategoryService(
        @WebParam(name = "categoryService", targetNamespace = "")
        CategoryService categoryService);

    /**
     * 
     * @return
     *     returns java.util.List<fr.alma.soa.boutique.domaine.model.dto.xsd.CustomerDto>
     */
    @WebMethod(action = "urn:getCustomers")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCustomers", targetNamespace = "http://impl.webservice.application.boutique.soa.alma.fr", className = "fr.alma.soa.boutique.application.webservice.impl.GetCustomers")
    @ResponseWrapper(localName = "getCustomersResponse", targetNamespace = "http://impl.webservice.application.boutique.soa.alma.fr", className = "fr.alma.soa.boutique.application.webservice.impl.GetCustomersResponse")
    public List<CustomerDto> getCustomers();

    /**
     * 
     * @param cartDto
     * @param newCurrency
     */
    @WebMethod(action = "urn:changeCurrency")
    @Oneway
    @RequestWrapper(localName = "changeCurrency", targetNamespace = "http://impl.webservice.application.boutique.soa.alma.fr", className = "fr.alma.soa.boutique.application.webservice.impl.ChangeCurrency")
    public void changeCurrency(
        @WebParam(name = "cartDto", targetNamespace = "")
        ShoppingCartDto cartDto,
        @WebParam(name = "newCurrency", targetNamespace = "")
        String newCurrency);

    /**
     * 
     * @param email
     * @return
     *     returns fr.alma.soa.boutique.domaine.model.dto.xsd.CustomerDto
     */
    @WebMethod(action = "urn:getCustomerByEmail")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCustomerByEmail", targetNamespace = "http://impl.webservice.application.boutique.soa.alma.fr", className = "fr.alma.soa.boutique.application.webservice.impl.GetCustomerByEmail")
    @ResponseWrapper(localName = "getCustomerByEmailResponse", targetNamespace = "http://impl.webservice.application.boutique.soa.alma.fr", className = "fr.alma.soa.boutique.application.webservice.impl.GetCustomerByEmailResponse")
    public CustomerDto getCustomerByEmail(
        @WebParam(name = "email", targetNamespace = "")
        String email);

    /**
     * 
     * @param product
     * @param quantity
     * @param customer
     * @return
     *     returns fr.alma.soa.boutique.domaine.model.dto.xsd.ShoppingCartDto
     */
    @WebMethod(action = "urn:addProductToCart")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addProductToCart", targetNamespace = "http://impl.webservice.application.boutique.soa.alma.fr", className = "fr.alma.soa.boutique.application.webservice.impl.AddProductToCart")
    @ResponseWrapper(localName = "addProductToCartResponse", targetNamespace = "http://impl.webservice.application.boutique.soa.alma.fr", className = "fr.alma.soa.boutique.application.webservice.impl.AddProductToCartResponse")
    public ShoppingCartDto addProductToCart(
        @WebParam(name = "customer", targetNamespace = "")
        CustomerDto customer,
        @WebParam(name = "product", targetNamespace = "")
        ProductDto product,
        @WebParam(name = "quantity", targetNamespace = "")
        Integer quantity);

    /**
     * 
     * @return
     *     returns java.util.List<fr.alma.soa.boutique.domaine.model.dto.xsd.CategoryDto>
     */
    @WebMethod(action = "urn:getAllCategories")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllCategories", targetNamespace = "http://impl.webservice.application.boutique.soa.alma.fr", className = "fr.alma.soa.boutique.application.webservice.impl.GetAllCategories")
    @ResponseWrapper(localName = "getAllCategoriesResponse", targetNamespace = "http://impl.webservice.application.boutique.soa.alma.fr", className = "fr.alma.soa.boutique.application.webservice.impl.GetAllCategoriesResponse")
    public List<CategoryDto> getAllCategories();

    /**
     * 
     * @param id
     * @return
     *     returns fr.alma.soa.boutique.domaine.model.dto.xsd.ProductDto
     */
    @WebMethod(action = "urn:getProductById")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductById", targetNamespace = "http://impl.webservice.application.boutique.soa.alma.fr", className = "fr.alma.soa.boutique.application.webservice.impl.GetProductById")
    @ResponseWrapper(localName = "getProductByIdResponse", targetNamespace = "http://impl.webservice.application.boutique.soa.alma.fr", className = "fr.alma.soa.boutique.application.webservice.impl.GetProductByIdResponse")
    public ProductDto getProductById(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @param customerService
     */
    @WebMethod(action = "urn:setCustomerService")
    @Oneway
    @RequestWrapper(localName = "setCustomerService", targetNamespace = "http://impl.webservice.application.boutique.soa.alma.fr", className = "fr.alma.soa.boutique.application.webservice.impl.SetCustomerService")
    public void setCustomerService(
        @WebParam(name = "customerService", targetNamespace = "")
        CustomerService customerService);

    /**
     * 
     * @param shoppingCartService
     */
    @WebMethod(action = "urn:setShoppingCartService")
    @Oneway
    @RequestWrapper(localName = "setShoppingCartService", targetNamespace = "http://impl.webservice.application.boutique.soa.alma.fr", className = "fr.alma.soa.boutique.application.webservice.impl.SetShoppingCartService")
    public void setShoppingCartService(
        @WebParam(name = "shoppingCartService", targetNamespace = "")
        ShoppingCartService shoppingCartService);

    /**
     * 
     * @param productService
     */
    @WebMethod(action = "urn:setProductService")
    @Oneway
    @RequestWrapper(localName = "setProductService", targetNamespace = "http://impl.webservice.application.boutique.soa.alma.fr", className = "fr.alma.soa.boutique.application.webservice.impl.SetProductService")
    public void setProductService(
        @WebParam(name = "productService", targetNamespace = "")
        ProductService productService);

    /**
     * 
     * @param id
     * @return
     *     returns fr.alma.soa.boutique.domaine.model.dto.xsd.CategoryDto
     */
    @WebMethod(action = "urn:getCategoryById")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCategoryById", targetNamespace = "http://impl.webservice.application.boutique.soa.alma.fr", className = "fr.alma.soa.boutique.application.webservice.impl.GetCategoryById")
    @ResponseWrapper(localName = "getCategoryByIdResponse", targetNamespace = "http://impl.webservice.application.boutique.soa.alma.fr", className = "fr.alma.soa.boutique.application.webservice.impl.GetCategoryByIdResponse")
    public CategoryDto getCategoryById(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @return
     *     returns java.util.List<fr.alma.soa.boutique.domaine.model.dto.xsd.ProductDto>
     */
    @WebMethod(action = "urn:getAllProductList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllProductList", targetNamespace = "http://impl.webservice.application.boutique.soa.alma.fr", className = "fr.alma.soa.boutique.application.webservice.impl.GetAllProductList")
    @ResponseWrapper(localName = "getAllProductListResponse", targetNamespace = "http://impl.webservice.application.boutique.soa.alma.fr", className = "fr.alma.soa.boutique.application.webservice.impl.GetAllProductListResponse")
    public List<ProductDto> getAllProductList();

    /**
     * 
     * @param category
     * @return
     *     returns java.util.List<fr.alma.soa.boutique.domaine.model.dto.xsd.ProductDto>
     */
    @WebMethod(action = "urn:getProductsByCategory")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductsByCategory", targetNamespace = "http://impl.webservice.application.boutique.soa.alma.fr", className = "fr.alma.soa.boutique.application.webservice.impl.GetProductsByCategory")
    @ResponseWrapper(localName = "getProductsByCategoryResponse", targetNamespace = "http://impl.webservice.application.boutique.soa.alma.fr", className = "fr.alma.soa.boutique.application.webservice.impl.GetProductsByCategoryResponse")
    public List<ProductDto> getProductsByCategory(
        @WebParam(name = "category", targetNamespace = "")
        CategoryDto category);

}
